export default
[
  {
    "name": "Henry",
    "breed": "Akita",
    "dob": "2015-10-09",
    "gender": "Male",
    "location": "Manchester",
    "description": "A gentle giant who loves long walks and quiet evenings at home.",
    "live_with_cats": false,
    "live_with_dogs": true,
    "live_with_children": true,
    "charity_name": "Doggie",
    "charity_number": "12345",
    "image": "https://i.imgur.com/4tVgBOT.jpeg"
  },
  {
    "name": "Suki",
    "breed": "Akita",
    "dob": "2019-08-14",
    "gender": "Female",
    "location": "Bristol",
    "description": "An energetic and loyal companion, ideal for an active family.",
    "live_with_cats": false,
    "live_with_dogs": true,
    "live_with_children": false,
    "charity_name": "Doggie",
    "charity_number": "12345",
    "image": "https://i.imgur.com/OHzmo9D.jpeg"
  },
  {
    "name": "Buddy",
    "breed": "Labrador Retriever",
    "dob": "2021-03-07",
    "gender": "Male",
    "location": "London",
    "description": "A friendly and playful dog who loves everyone he meets.",
    "live_with_cats": true,
    "live_with_dogs": true,
    "live_with_children": true,
    "charity_name": "Happy Tails Shelter",
    "charity_number": "67890",
    "image": "https://i.imgur.com/s3RYVh1.jpeg"
  },
  {
    "name": "Daisy",
    "breed": "Cocker Spaniel",
    "dob": "2017-09-25",
    "gender": "Female",
    "location": "Liverpool",
    "description": "A sweet and gentle girl who enjoys cuddles and quiet walks.",
    "live_with_cats": true,
    "live_with_dogs": true,
    "live_with_children": true,
    "charity_name": "Paws and Claws Rescue",
    "charity_number": "11223",
    "image": "https://i.imgur.com/WxFeqTc.jpeg"
  },
  {
    "name": "Max",
    "breed": "German Shepherd",
    "dob": "2015-05-18",
    "gender": "Male",
    "location": "Birmingham",
    "description": "A smart and loyal protector looking for an experienced owner.",
    "live_with_cats": false,
    "live_with_dogs": true,
    "live_with_children": false,
    "charity_name": "Safe Haven Dogs",
    "charity_number": "33445",
    "image": "https://i.imgur.com/JuOwJTW.jpeg"
  },
  {
    "name": "Luna",
    "breed": "Border Collie",
    "dob": "2024-11-12",
    "gender": "Female",
    "location": "Edinburgh",
    "description": "An intelligent and energetic dog who loves learning new tricks.",
    "live_with_cats": false,
    "live_with_dogs": true,
    "live_with_children": true,
    "charity_name": "Highland Rescue",
    "charity_number": "55678",
    "image": "https://i.imgur.com/AXHNqpn.jpeg"
  },
  {
    "name": "Charlie",
    "breed": "Beagle",
    "dob": "2019-07-30",
    "gender": "Male",
    "location": "Cardiff",
    "description": "A curious and loving dog who enjoys exploring and sniffing new scents.",
    "live_with_cats": true,
    "live_with_dogs": true,
    "live_with_children": true,
    "charity_name": "South Wales Rescue",
    "charity_number": "77889",
    "image": "https://i.imgur.com/rY1vP68.jpeg"
  }
]