const dogBreeds = {
    akita: "Akita",
    australian_shepherd: "Australian Shepherd",
    basset_hound: "Basset Hound",
    beagle: "Beagle",
    border_collie: "Border Collie",
    boxer: "Boxer",
    bulldog: "Bulldog",
    cavalier_king_charles: "Cavalier King Charles",
    chihuahua: "Chihuahua",
    cocker_spaniel: "Cocker Spaniel",
    dachshund: "Dachshund",
    dalmatian: "Dalmatian",
    doberman_pinscher: "Doberman Pinscher",
    english_springer_spaniel: "English Springer Spaniel",
    french_bulldog: "French Bulldog",
    german_shepherd_dog: "German Shepherd Dog",
    golden_retriever: "Golden Retriever",
    great_dane: "Great Dane",
    husky: "Husky",
    labrador_retriever: "Labrador Retriever",
    maltese: "Maltese",
    miniature_schnauzer: "Miniature Schnauzer",
    pomeranian: "Pomeranian",
    poodle: "Poodle",
    pug: "Pug",
    rottweiler: "Rottweiler",
    samoyed: "Samoyed",
    staffordshire_bull_terrier: "Staffordshire Bull Terrier",
    whippet: "Whippet",
    yorkshire_terrier: "Yorkshire Terrier",
    shih_tzu: "Shih Tzu",
    other_crossbreed: "Other Crossbreed",
}

export default dogBreeds